name: Application CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


permissions:
  contents: read
  packages: write
  

jobs:

  python-ci:

    uses: ANANTHALAKSHMI-REDNAM/github-actions-reusable-workflow/.github/workflows/reusable-ci.yml@main

    with:
      python-version: "3.12"
      docker-image: ghcr.io/ananthalakshmi-rednam/github-actions-level4-poc

    secrets:
      POC_MESSAGE: ${{ secrets.POC_MESSAGE }}