name: Application CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  python-ci:

    uses: ANANTHALAKSHMI-REDNAM/github-actions-reusable-workflow/.github/workflows/reusable-ci.yml@main

    with:
      python-version: "3.12"
      docker-image: ghcr.io/ananthalakshmi-rednam/github-actions-reusable-poc-2
      version: ${{ github.ref_name }}

    secrets:
      POC_MESSAGE: ${{ secrets.POC_MESSAGE }}